Webpack 5: Update configuration for `url-loader`
Error: Compiling RuleSet failed: Query arguments on 'loader' has been
removed in favor of the 'options' property.
(at ruleSet[1].rules[2].loader: url-loader?limit=10000)